### ISSUE TITLE
trf_barier does not imply bollard

### ISSUE THREAD

**Issue by RobJN** [cyclestreets/tflcid-conversion#12]
As per this example ([RWG072095](https://api.cyclestreets.net/v2/infrastructure.image?key=c047ed46f7b50b18&dataset=tflcid&id=RWG072095&variant=2)) It can mean other forms of barrier.

Use simple barrier=yes instead. Alternatively some interface to let users pick the barrier type or collect extra data using [Pic4Review](https://pic4review.pavie.info/#/).

**Comment by mvl22** [comment]
Correct.

This was picked up during implementation:
https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/traffic_calming_barriers.rb#L32-L33

has `"barrier"=> "yes"`.

No action needed.

**Comment by rskedgell** [comment]
If it's barrier=yes, then access=no + bicycle=yes + foot=yes *cannot* be assumed. It needs to be checked against the TfLCID photographs before it's imported, otherwise we may get broken motor vehicle routing. Surely the appropriate action for TRF_BARRIER should be "either find out what it is and tag appropriately, or simply don't import it".

We already have 197 of these nodes imported, mostly as part of phase 1. These still need to be reviewed.

**Comment by mvl22** [comment]
> If it's barrier=yes, then access=no + bicycle=yes + foot=yes cannot be assumed.

Hmm, yes. This problem derives from an ambiguity in the spec. 'Barrier that cyclists can pass' could imply 'where motorists' can't, otherwise it probably wouldn't be in the database at all as it wouldn't then be cycle infrastructure. However, as you say there could be cases where it's a barrier like a gate which is open.

I think to be safe it's probably safest for Richard to remove the `access=no` at this stage.

Action: @systemed Assuming you agree with the above:

- In the code, remove the `access=no`
- I will ask the project team to check against the photos
- I will ask the project team to review the existing 197
