### ISSUE TITLE
Cycle parking: covered

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/tflcid-conversion#17]
Robert Norris wrote in:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023515.html

"It would be good to capture `covered=yes/no` - but this I assume is not in the TFL data (unless it can be derived from individual photographs)."

**Comment by mvl22** [comment]
Rob Nickerson wrote in:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023517.html

"
>It would be good to capture covered=yes/no - but this I assume is not in the TFL data

TfL have spent a massive amount of time collecting some super data. Covered was indeed one of the things they recorded:
https://bikedata.cyclestreets.net/tflcid/conversion/#prk_cover "

**Comment by peternewman** [comment]
Hi @mvl22 ,

I didn't seem to see covered being set on the bike parking, e.g. https://www.openstreetmap.org/node/10280272989#map=17/51.60459/-0.33753 until I added it myself.

Looking at, was it only tagged for when they were covered?
https://github.com/cyclestreets/tflcid-conversion/blob/a396026309b871f967f76ce5574c36bc3463076b/schema/schema.json#L810-L827

If so that's a bit unfortunate as StreetComplete will still ask people for all the ones where it's not tagged at all.
