### ISSUE TITLE
Feeder lane in centre / on right / on left

### ISSUE THREAD

**Issue by RobJN** [cyclestreets/tflcid-conversion#2]
The proposed tag "asl_position=left|right|center" seems odd, possibly even wrong. In my view the ASL position is given by the node cycleway=asl and given that ASL run the full width of the road for the direction of travel (i.e. up to the mid line for 2 way streets) any other concept of position seems weird.

I think what you are looking for is the **feeder position**. 

Linking in with #1 perhaps something like:

- asl:feeder=right|left|center

Or if possible to have more than one at the same time then:

- asl:feeder:right = yes
- asl:feeder:left = yes

P.S. "center" or "centre" or just "middle"?

**Comment by RobJN** [comment]
Just reviewed [TfL's guide](https://cycling.data.tfl.gov.uk/CyclingInfrastructure/documentation/asset_information_guide.pdf) and they state:

> Some ASLs will have more than one feeder lane in which case the attribute for each type present were set at ‘True’.

As such we need to cater for the case of multiple feeders into a single ASL.

**Comment by jnicho02** [comment]
Remember to fight for the right to keep British English the primary language of OSM "centre"....although it could be a fight ;)

**Comment by mvl22** [comment]
Posting on talk-gb at:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023513.html

**Comment by mvl22** [comment]
Rob also noted:

"more importantly it doesn't allow for mixed cases such as Right AND Left). The TfL guide suggests mixed cases are possible. Can you see any in the data?"

**Comment by mvl22** [comment]
Richard Fairhurst wrote in:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023522.html

"Yes, although the lingua franca of OSM is British English so it should be "centre"."

**Comment by mvl22** [comment]
I wrote in:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023563.html

"(Can't believe I didn't spot the "center" spelling and "mandatory" issue myself - like the other points these are all definitely changes that should be made!)"

**Comment by mvl22** [comment]
> I think what you are looking for is the **feeder position**.

Yes, sorry.

> asl:feeder=right|left|center

This seems correct to me. The :left etc syntax has the downside that it doesn't provide future-proofing, e.g. a feeder lane entering the second of four lanes, etc. The [wiki page](https://wiki.openstreetmap.org/wiki/Tag:cycleway=asl) is otherwise silent on this.

Where there is more than one, the pipe syntax can be used as normal.

The CID spec for this is at:
https://bikedata.cyclestreets.net/tflcid/conversion/#asl_fdr

> "Yes, although the lingua franca of OSM is British English so it should be "centre"."

Noted. It would also be pretty odd for a road device only prevalent in Britain to be using US spelling :)

@systemed Action here is:

- We currently seem not to have basic implementation of `ASL_FDR=YES` which is classed as LineString as per OSM. So that needs to be put in place.
- Where `ASL_FDR=YES` then check for each of `ASL_FDRLFT=YES`, `ASL_FDCENT=YES`, `ASL_FDRIGH+YES` and map to `asl:feeder=left`, `asl:feeder=centre`, `asl:feeder=right` respectively. I suggest adding each to an array that is then imploded with | to deal with more than one, e.g. `asl:feeder=left|right`.

**Comment by systemed** [comment]
We don't currently read the CID ASL data at all so this will need a new reader.

**Comment by systemed** [comment]
New reader added in https://github.com/cyclestreets/tflcid-conversion/commit/ebf1f900ecdcb45f8a9778dbab6c0cebf7131a75.
