### ISSUE TITLE
Hybrid (stepped) cycle track

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/tflcid-conversion#23]
Richard Fairhurst wrote in:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023522.html

> cycleway:track=hybrid is proposed as a backwards-compatible 
> addition that elaborates on cycleway=track.

"That makes sense when it's mapped as `cycleway=track` on a single road centreline. I can however envisage hybrid cycleways often being mapped as a separate `highway=cycleway`, particularly when it's part of a continuous route which is sometimes kerbed and sometimes hybrid. `highway=cycleway; cycleway:track=hybrid` is a slightly unintuitive tag combination. It's not a massive deal but I wonder whether `cycleway_type=hybrid` might be better here."

**Comment by mvl22** [comment]
Twitter user "ParisBeauAVelo" wrote at:
https://twitter.com/ParisBeauAVelo/status/1179511503424249860
https://twitter.com/ParisBeauAVelo/status/1179515678564503562

"cycleway:track=hybrid
It is good idea to be able to precise the type of a cycle track, I'm thinking also of the issue of Barcelona's cycle lane/track like https://i1.wp.com/bicilonatours.com/wp-content/uploads/2017/02/barcelona-cr-urgell.png
Scheme is ok. I might like to be able also to precise the height of the edge"

"And I don't like "hybrid" value, it doesn't mean anything, stepped is better.
In Paris there is already higheway=cycleway cycleway=on_street/on_pavement btw"

**Comment by b33k34** [comment]
Seconded ParisBeauAVelo

would be good to differentiate between (in order of levels of protection) 
- painted on road cycle lane 
- semi-segregated/soft protected  track (intermittent protection with orcas/wands/planters) 
- kerb protected track (at road level with continuous protection) 
- stepped track (at intermediate level between road and footway)

**Comment by mvl22** [comment]
Obviously, painted on-road cycle lanes are tagged as `cycleway=lane`, and kerb-protected track as `cycleway=track`. The other two are variants on hybrid.

**Comment by b33k34** [comment]
Given the multitude of different ways of giving some protection to cyclists I wonder whether it is better to treat them all as variants of track (since they all offer much greater protection than a lane but vary in comfort level - in my view in this order of comfort). 

cycleway:track=kerb
cycleway:track=rubber_kerb_wand
cycleway:track=rubber_kerb
cycleway:track=stepped
cycleway:track=wandorca
cycleway:track=wand
cycleway:track=orca

There may be more I've forgotten

**Comment by mvl22** [comment]
This whole area of cycleway light segregation, a type of infrastructure in the UK which has become significantly more prevalent during the pandemic, has now moved on quite a lot in OSM tagging terms:

https://wiki.openstreetmap.org/wiki/Proposed_features/separation

which in my view is a well-considered specification. Would you agree @systemed?

[Taginfo](https://taginfo.openstreetmap.org/keys/separation#values) shows this is starting to be used.

**Comment by mvl22** [comment]
In the [CID spec](https://bikedata.cyclestreets.net/tflcid/conversion/#clt_stepp) we have these:

`CLT_PARSEG` - 'Partially or light segregated lane/track'
`CLT_STEPP` - 'Stepped lane/track'

Currently two are handled by writing in `cycleway:track=hybrid` / and also variant `cycleway:left:track` in this [first](https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/clt_roads.rb#L121-L128) and [second](https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/tfl_common.rb#L284) place in the code.

[Taginfo shows](https://taginfo.openstreetmap.org/keys/cycleway:track#values) that stepped isn't in use, but hybrid isn't really either. I suggest we change hybrid to stepped as the above comments indicate it is clearer to people.

However, the main change is to add in support for cycleway:separation / separation, now that standard exists.

[Taginfo shows](https://taginfo.openstreetmap.org/keys/cycleway:separation#values) there is little use yet, as would be expected. This has `kerb` in use, and this matches the [example photo](https://bikedata.cyclestreets.net/tflcid/conversion/#clt_stepp).

@systemed So the action here is:

- To improve the implementation of `CLT_PARSEG `, change `cycleway:track=hybrid` / `cycleway:left:track=hybrid` to be 'stepped` instead of hybrid.
- To implement `CLT_STEPP=TRUE`, we should also add `cycleway:separation=step` / `cycleway:left:separation=step` where it is part of the road, or `separation=step` where it is drawn as a separate track.

**Comment by rskedgell** [comment]
@mvl22 How should the separation be tagged when the cycle track is already mapped as a separate highway=cycleway? This is more likely, particularly in the case of CLT_STEPP.

If there is a CLT_PARSEG mandatory lane with added orcas or wands, does it remain in law as an exclusive lane, rather than becoming a cycle track?

**Comment by mvl22** [comment]
> How should the separation be tagged when the cycle track is already mapped as a separate highway=cycleway? This is more likely, particularly in the case of CLT_STEPP.

As `separation=step` as noted above.

> If there is a CLT_PARSEG mandatory lane with added orcas or wands, does it remain in law as an exclusive lane, rather than becoming a cycle track?

It would surely depend on the TRO (or rather Traffic Order in London), as to whether the TRO defines a lane or a track. I don't think the addition of orcas or wands counts as having any legal status. However, I don't think this changes the tagging.

**Comment by rskedgell** [comment]
Thanks for the clarification. As far as I am aware, no traffic order is required to add wands or orcas to a mandatory cycle lane (I agree that they are unlikely to have any legal status, so nothing has really changed for traffic regulation), so that would be cycleway:$side=lane + cycleway:$side:lane=exclusive + cycleway:$side:separation:*=flex_post|lane_separator

I'd rather we didn't suddenly acquire cycle tracks which are actually lanes in the same way we recently acquired unchecked barrier=yes nodes (with very specific access tags for barriers of unknown type). There are implications for CCTV parking enforcement (which applies to all of England, including Greater London).

**Comment by mvl22** [comment]
> I'd rather we didn't suddenly acquire cycle tracks which are actually lanes

I think there is a distinction though between the legal status and how people perceive it. I would see orcas added to a lane within the road as being **experienced** as a track, because the user doesn't have to worry about traffic in the same way as a fully segregated track. I'd really rather we didn't try to open a can of worms here. My experience in OSM editing is that light segregation on a road is more often done as track within a road, which implements the concept under discussion here of 'hybrid' provision. I'm not saying lane would be wrong, but I think it is arguable that people could do it either way, and what we have currently is one of those two ways.

Certainly if I was manually tagging I would be upgrading from lane within the road to being a track within the road, as these reflect properly the fundamental safety level that a specialist cycle routing engine would be judging quite differently.

**Comment by rskedgell** [comment]
Noted, although orcas and wands deter rather than prevent encroachment by motor vehicles, so users have to worry less rather than not at all. Wands also have a tendency to disappear, with replacement rates dependent on the attitude of the responsible highway authority. Treating wand segregated lanes as tracks might give rather more confidence than is warranted.

Ultimately, I'd prefer to follow tagging schemas which your and @systemed 's routers can actually make use of than dispute minor legal points. I also want the second attempt at the TfLCID import to be a success.

**Comment by systemed** [comment]
Just to clarify:

> * To improve the implementation of `CLT_PARSEG `, change `cycleway:track=hybrid` / `cycleway:left:track=hybrid` to be 'stepped` instead of hybrid.

We don't want to represent CLT_PARSEG as `cycleway:track=stepped`, because it's probably wands or orcas. For example, Birdcage Walk is in the CID as CLT_PARSEG, and that's wands.

As @rskedgell says we could use

> cycleway:$side:separation:*=flex_post|lane_separator

but we have the problem there that we don't know that it _is_ a `flex_post` (or whatever).

We could, I guess, map it as `cycleway:(side):separation=yes` or `=light`: these are inconclusive and an implied fixme, but the most true representation of what we know from the CID.

**Comment by mvl22** [comment]
> We could, I guess, map it as cycleway:(side):separation=yes or =light: these are inconclusive and an implied fixme, but the most true representation of what we know from the CID.

Yes, that's fine.

Please do go ahead and implement.
