### ISSUE TITLE
clt_parkr proposes adding bicycle=yes to highway=cycleway in rare cases

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#29]
`TRUE: bicycle=yes IF geometry not already present, also add highway=cycleway`
`Maintain existing highway type (i.e. footway vs cycleway)`

So in case of existing `highway=cycleway` it would add `bicycle=yes`? It sounds incorrect to me.

----

note to self: I reviewed only small part of https://bikedata.cyclestreets.net/tflcid/conversion/

After my comments are processed I will either reraise them at talk-gb or continue reading https://bikedata.cyclestreets.net/tflcid/conversion/

**Comment by mvl22** [comment]
Thanks for flagging this up. It's also not well formatted and is not 100% clear. I will update it to make clear what I was trying to explain.

https://bikedata.cyclestreets.net/tflcid/conversion/#clt_parkr
Park Route - clt_parkr

This should be:

"TRUE: `bicycle=yes`."

i.e. if the data is TRUE then set `bicycle=yes` (if the geometry is already present and is set to `highway=footway`).

"IF geometry not already present, instead add it, using `highway=cycleway`"

i.e. if not already present, create a new cycleway.

"Maintain existing highway type (i.e. footway vs cycleway)"

This is an additional note that if there is already a geometry present, then do not disrupt its type, but just ensure that bicycle is clearly permitted. I.e. either
`highway=footway, bicycle=yes`
OR
`highway=cycleway`
in order to respect the original mapper who judged whether this is a footway or a cycleway. (In the UK, we have footways that can legally be cycled on, whereas a cycleway is generally considered to be of a higher overall quality - it's not a clear distinction unfortunately.)

**Comment by matkoniecz** [comment]
In that case it is just unclear documentation, though improving it should be fine before an import.

**Comment by mvl22** [comment]
> In that case it is just unclear documentation, though improving it should be fine before an import.

Thanks for flagging up that this was not at all clear!

**Comment by mvl22** [comment]
Documentation presentation fixed in bb2df32881a4e3356d9089b0b267f8c967501b75.
