### ISSUE TITLE
Conversion: amenity=bicycle_parking

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/tflcid-conversion#35]
The new bicycle parking layer has tags such as the stand type and capacity, but doesn't actually contain the core `amenity=bicycle_parking` tag; accordingly, when saved into OSM, it shows up as a point of unknown type.

**Comment by systemed** [comment]
Fixed in https://github.com/cyclestreets/tflcid-conversion/commit/5a3a9b79d1ce015a2c0a1445bcad1c9b108f01f6 .

I've also made the "existing OSM parking" files optional, as they're rather different to everything else which is new/changed data - they can be created by passing `--existing` when calling the Ruby script.
