### ISSUE TITLE
Cycle parking lockers - use of own lock or provided lock

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#37]
I noticed in dataset linked on mailing lists that this import wants to invent a new tag - `bicycle_parking=locked`, typically with `note=Own lock`

please, use standard `access=private`. Note that `bicycle_parking=locked` is making impossible to tag type of bicycle parking

(spotted on id RWG102738)

**Comment by InsertUser** [comment]
Does "own lock" mean the user must supply the lock, or the facility owner supplies the lock?

**Comment by mvl22** [comment]
> Note that bicycle_parking=locked is making impossible to tag type of bicycle parking

Agreed that attributes like 'locked' should not be in the same namespace as the [`bicycle_parking` core namespace](https://wiki.openstreetmap.org/wiki/Key:bicycle_parking), which is concerned with type and not other metadata. As shown in the [code](https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/parking.rb) this has not been implemented anyway.

**Comment by mvl22** [comment]
I don't think `note=Own lock` implies `access=private`. All it tells you is that a facility, whether public or private, requires use of your own lock, rather than it having an inbuilt mechanism.

As the [code](https://github.com/cyclestreets/tflcid-conversion/blob/68fb091ad20e4a465d7f3faad1059c66dfc01ddf/readers/parking.rb#L86) shows, are being used in combination with `bicycle_parking=lockers`. These do not in themselves imply `access=private`. For instance, you can have cycle parking which is openly advertised to the public.

So I think the conversion is correct and therefore no action is needed on this one.

**Comment by matkoniecz** [comment]
> I don't think note=Own lock implies access=private. All it tells you is that a facility, whether public or private, requires use of your own lock, rather than it having an inbuilt mechanism.

Oh, so it refers to U-lock? Not to lock to the storage?

I understood it that it is some locked storage and users have own locks.

Given that bringing own U-lock is completely normal I would not add extra tags about this.

**Comment by mvl22** [comment]
> Oh, so it refers to U-lock? Not to lock to the storage?

There are two fields which collectively represent a locker and whether the lock is provided by the operator vs the user:

- [PRK_LOCKER](https://bikedata.cyclestreets.net/tflcid/conversion/#prk_locker)
- [PRK_SECURE](https://bikedata.cyclestreets.net/tflcid/conversion/#prk_secure)

These are implemented [in the code](https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/parking.rb#L85-L86) correctly. I see no reason not to add a note giving this fine-grained detail, since it is easy to do so. It works fine and is not causing excessive clutter.

**Comment by matkoniecz** [comment]
`note=Own lock` and `note=Shared lock` would be still really unclear if seen in OSM, but I am not from UK so maybe I am unduly confused.

**Comment by mvl22** [comment]
We could change these to:

- User should bring own lock
- The locker has its own locking system

Do these seem clearer to you?

**Comment by matkoniecz** [comment]
Yes, though likely some more standard tagging like `bicycle_lock=provided` or `bicycle_lock=bring_own` would be better (though tags should be consulted with community).

Putting it into note is asking for `note=Trzeba przynieść swój` used elsewhere and ending with data not even hypothetically parsable - note that `note` is for freeform notes to other mappers. See https://wiki.openstreetmap.org/wiki/Key:note

**Comment by mvl22** [comment]
> Yes, though likely some more standard tagging like bicycle_lock=provided or bicycle_lock=bring_own would be better (though tags should be consulted with community).

Yes, I agree those two tags would work well. They are clear, and are preferable to a note.

**Comment by matkoniecz** [comment]
> bicycle_lock=provided or bicycle_lock=bring_own

And to be clear this tags are ATYL on the spot invention and I have not even checked either wiki or taginfo.

+1 to consult_on_talkgb

**Comment by mvl22** [comment]
> And to be clear this tags are ATYL on the spot invention and I have not even checked either wiki or taginfo.

I did check both; these aren't in use yet but it's not exactly a major detail.

**Comment by mvl22** [comment]
> And to be clear this tags are ATYL on the spot invention and I have not even checked either wiki or taginfo.

I did check both; these aren't in use yet but it's not exactly a major detail.

**Comment by mvl22** [comment]
Raised on talk-gb at:
https://lists.openstreetmap.org/pipermail/talk-gb/2022-August/029244.html

**Comment by mvl22** [comment]
NB Andy commented at
https://lists.openstreetmap.org/pipermail/talk-gb/2022-August/029248.html
but I don't think this changes the implementation.
