### ISSUE TITLE
Side road entry treatment - TRF_ENTRY (raised in some way including continuous footway)

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#38]
https://bikedata.cyclestreets.net/tflcid/conversion/#trf_entry

![RWG032637](https://user-images.githubusercontent.com/899988/135580083-0d3f4683-f55f-4176-bd7f-7132a99e634a.jpg)

This looks like `traffic_calming=table` to me, just placed on crossing of side road and sidewalk.

Some new tag is needed if sidewalk is mapped as a tag on road, not a separate way

BTW,

> OSM currently has no notion of representing a continuous sidewalk. Could be represented on the Node as sidewalk=yes,continuous=yes, or on the Way where the pavement is separately represented. Continuous would be a new tag. If community is divided, represe

is unfinished/cut off

**Comment by rskedgell** [comment]
Importing these as nodes tagged only with continuous=yes + sidewalk=yes is perhaps a little unhelpful, since I need to go back to TfLCID to find out what the node represents. Many of the ones I have seen are better described as highway=crossing + traffic_calming=table under current tagging practices in London. In many cases, there is tactile paving either side of the side road and the give way markings are on the side road between the crossing and the main road, so neither continuous=yes or sidewalk=yes seem particularly appropriate.

Only a small proportion are really the continuous sidewalk "Copenhagen crossings" used by (e.g.) London Borough of Waltham Forest. These have a give way marking on the side road before the crossing, and the sidewalk really is continuous. The best way to tag these probably needs a proposal and community discussion, but adding highway=crossing to the import's continuous=yes + sidewalk=yes could be helpful if/when some consensus emerges.
https://enjoywalthamforest.co.uk/blended-copenhagen-crossings/

Examination of TfL's survey photographs linked in TfLCID as part of the conflation process should make it fairly straightforward to decide what sort of OSM feature a TRF_ENTRY asset represents.

**Comment by mvl22** [comment]
_Transferred from: https://github.com/cyclestreets/tflcid-conversion/issues/16#issue-506058388 :_

--

Suggestion from Jez C:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023514.html

"• Side-road entry treatment:

The `sidewalk=yes` tag is already in use as an attribute of `highway=*` when it is not known which side(s) of a street has sidewalks.

I would tag this node as `highway=crossing` and `traffic_calming=table`. 

If the adjacent highway already has `cycleway:sideroad_continuity=yes` I'm not convinced why you need a `continuous=yes` tag on the crossing node as well especially as there appears to be `tactile_paving` on the example photo too. 

Is there something special about these crossings that vehicles/cyclists turning into/out of the side-road must give way to pedestrians?"

**Comment by mvl22** [comment]
_Transferred from https://github.com/cyclestreets/tflcid-conversion/issues/16#issuecomment-541232411 :_

--

Richard Fairhurst wrote in:
https://lists.openstreetmap.org/pipermail/talk-gb/2019-September/023522.html

> A new tag cycleway:sideroad_continuity=yes is proposed as a backwards-compatible addition that elaborates on cycleway={lane|track}.

"Good concept but the tag is a little wordy. I wonder if a simple node at the junction tagged with "priority=cycleway" would be less verbose, and also permit "priority=road" for those situations where the sideroad has priority (this is sadly probably implicit, but it's good to tag out ambiguity)."

**Comment by mvl22** [comment]
_Transferred from https://github.com/cyclestreets/tflcid-conversion/issues/16#issuecomment-578497929 :_

--

systemed commented:

Thread at https://lists.openstreetmap.org/pipermail/tagging/2020-January/050557.html (also #30)

**Comment by mvl22** [comment]
_Transferred from https://github.com/cyclestreets/tflcid-conversion/issues/16#issuecomment-578497929 :_

--

systemed commented:

Thread at https://lists.openstreetmap.org/pipermail/tagging/2020-January/050557.html (also #30)

**Comment by mvl22** [comment]
Currently we implement this [in the code](https://github.com/cyclestreets/tflcid-conversion/blob/master/readers/traffic_calming_sideroads.rb#L26) as

`{ "sidewalk"=> "yes", "continuous"=>"yes", ...}`

 > adding highway=crossing to the import's continuous=yes + sidewalk=yes

I think that is worth adding - the presence of physical infrastructure makes this be an actual designated crossing point, so `highway=crossing` should indeed be added, which is clearly in line with the [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway=crossing) spec. 'raised in some way including continuous footway' makes this unambiguous.

I would also suggest that we improve on `continuous` by namespacing it to foot only, i.e. `foot:continuous=yes`. I see no downside to doing so, not least as there aren't any data consumers of this yet, and this improves clarity.

There is an overall need for community discussion on how to deal with continuous footways and raised crossings, but our current implementation is good enough, and I think a fully-comprehensive implementation is probably beyond the scope of this project. However, it provides some data which should work as a starting point.

> Good concept but the [sideroad_continuity] tag is a little wordy. I wonder if a simple node at the junction tagged with "priority=cycleway" would be less verbose, and also permit "priority=road" for those situations where the sideroad has priority (this is sadly probably implicit, but it's good to tag out ambiguity)."

I think `priority=cycleway` would be ambiguous where the sideroad itself also has a cycleway, which could easily happen for instance with a contraflow. So I suggest we upgrade `priority` to `sideroad_continuity`, which is in fact what we are already doing in #30, so we need to fix that inconsistency anyway.

The documentation **explicitly lists these under traffic calming**, and they are 'raised', so we can add to the node that it is `traffic_calming=table`

@systemed Action:

- Add `highway=crossing`
- Add `traffic_calming=table`
- Change `continuous=yes` to `foot:sideroad_continuity=yes`

**Comment by rskedgell** [comment]
Re side road entry treatment

> Is there something special about these crossings that vehicles/cyclists turning into/out of the side-road must give way to pedestrians?"

Some of these are a real continuous footway, as in RWG147603 in Waltham Forest. These always have give way markings on the side road before the crossing. If the footway/sidewalk is foot only, they have a continuous surface and no tactile dot paving. This example has tactile corduroy paving because of a change from segregated to unsegregated on the shared cycleway.
https://cycleassetimages.data.tfl.gov.uk/RWG147603_2.jpg

Others, probably the majority, are just crossings combined with a table. They will usually have tactile_paving=yes (dots) and kerb=flush. The pedestrian line is not necessarily continuous.
