### ISSUE TITLE
oneway=no is not really needed, unless actually needed

### ISSUE THREAD

**Issue by matkoniecz** [cyclestreets/tflcid-conversion#47]
https://bikedata.cyclestreets.net/tflcid/conversion/#clt_bidire

> If geometry is dedicated cycleway, use simple oneway=no rather than oneway:bicycle=no

why tag anything in such cases?

**Comment by mvl22** [comment]
Because in the UK, while some cycleways can be one-directional, this is not always the case, e.g. those alongside a road that are mapped as a separate way. E.g. 

https://www.openstreetmap.org/edit?way=49996516#map=19/52.17943/0.14240

So it's helpful, given that we know it is two-way, to say so explicitly, even though most are indeed two-way.
