### ISSUE TITLE
Addressing the "query" comment on crs_segreg 

### ISSUE THREAD

**Issue by RobJN** [cyclestreets/tflcid-conversion#8]
The query comment on crs_segreg asks (when fixed with #7) "does ~~un~~segregated imply no pedestrians". In general the answer to this question seems to mostly be "no" but there are a few cases:

1. Segregated crossing where cyclists cross immediately next to pedestrians ([example is RWG151443](https://api.cyclestreets.net/v2/infrastructure.image?key=c047ed46f7b50b18&dataset=tflcid&id=RWG151443&variant=1))
2. Segregated crossing where cyclists cross a couple meters away from pedestrians ([example is RWG081880](https://api.cyclestreets.net/v2/infrastructure.image?key=c047ed46f7b50b18&dataset=tflcid&id=RWG081880&variant=2)).
3. Segregated crossing where cyclists cross further/differently to pedestrians ([example is RWG065988](https://api.cyclestreets.net/v2/infrastructure.image?key=c047ed46f7b50b18&dataset=tflcid&id=RWG065988&variant=1))

From what I have seen so far this seems to be a good case where, on conflation, using the images and carefully checking the OSM data is going to be important.

**Comment by RobJN** [comment]
Ah so this is where conflation becomes more challenging. If we look again at that RWG065968 example we see two crossings mapped in OSM. The cycle crossing and the pedestrian crossing. If you look carefully you can just about see the pedestrian crossing in the TfL photos.

![image](https://user-images.githubusercontent.com/5060210/65359349-27569680-dbf4-11e9-8a11-6f77ebe81641.png)

This one has the cycle gap = TRUE attribute so maybe there is some value in it when we come to conflation -> i.e. cases with cycle gap = TRUE are likely going to need extra care.

**Comment by mvl22** [comment]
I've looked at a selection and every case I looked at does indeed show a separate space for cyclists and walkers. So this is as documented I believe.

We are also implementing this correctly in my view.

`if attrs['CRS_SEGREG'] then osm_tags['segregated'] = "yes" end`

I think the confusion I introduced here is because the segregation may be merely side-by-side rather than having a full gap. Nonetheless, there is segregation.

No action needed.
